config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :show, :new, :create, :edit, :update]
  resources :authors, except: [:delete]
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base

  validate :is_title_case 
  before_validation :make_title_case 
  belongs_to :author

  private

  def is_title_case
    if title.split.any?{|w|w[0].upcase != w[0]}
      errors.add(:title, "Title must be in title case")
    end
  end

  def make_title_case
    self.title = self.title.titlecase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    redirect_to author_path(@author)
  end

  def create
    @author = Author.create(author_params)
    redirect_to author_path(@author)
  end

  def new
    @author = Author.new
  end

  private

  def author_params
    params.require(:author).permit(:bio, :name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
	  @post = Post.new(params)
	  @post.save
	  redirect_to post_path(@post)
	end

	def update
	  @post = Post.find(params[:id])
	  @post.update(params.require(:post))
	  redirect_to post_path(@post)
	end

	def edit
	  @post = Post.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author</h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Blog Authors</h1>
<%= link_to "Add Author", new_author_path %>
<ul>
<% @authors.each do |author| %>
  <li>
  <%= link_to author.name, author_path(author) %><br>
  <%= author.bio %>
  </li>
<% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<p><%= @author.bio %></p>
<p>Posts:</p>
<% @author.posts.each do |post| %>
  <div><%= post.title %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogFlash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :title %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<%= form_for(@post) do |f| %>
  <label>Post title:</label><br>
  <%= f.text_field :title %><br>

  <label>Post Description</label><br>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div><%= post.title %></div>
<% end %>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <label>Post title:</label><br>
  <%= f.text_field :title %><br>

  <label>Post Description</label><br>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.description %></p>